python3 train.py peucrl_minus_r_minus_safety polarisation_13.json juju_peucrl_minus_safety_3
python3 train.py peucrl_minus_r polarisation_13.json juju_peucrl_3
python3 train.py peucrl_minus_r_minus_shield polarisation_13.json juju_peucrl_minus_shield_3
python3 train.py peucrl_minus_r_minus_action_pruning polarisation_13.json juju_peucrl_minus_action_pruning_3

python3 train.py peucrl_minus_r_minus_safety polarisation_14.json juju_peucrl_minus_safety_4
python3 train.py peucrl_minus_r polarisation_14.json juju_peucrl_4
python3 train.py peucrl_minus_r_minus_shield polarisation_14.json juju_peucrl_minus_shield_4
python3 train.py peucrl_minus_r_minus_action_pruning polarisation_14.json juju_peucrl_minus_action_pruning_4

python3 train.py peucrl_minus_r_minus_safety polarisation_15.json juju_peucrl_minus_safety_5
python3 train.py peucrl_minus_r polarisation_15.json juju_peucrl_5
python3 train.py peucrl_minus_r_minus_shield polarisation_15.json juju_peucrl_minus_shield_5
python3 train.py peucrl_minus_r_minus_action_pruning polarisation_15.json juju_peucrl_minus_action_pruning_5